---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4"
