# kubernetes/flux/repositories/flamingo-helm-repo.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flamingo
  namespace: flux-system
spec:
  interval: 1m
  url: https://argoproj.github.io/argo-helm
