apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5G2EzFn6bpsywngoxukY6ddpXHlH3RNSp2MzQ7BHZrPIzyX6,iv:onQJFcpOokwO7N03ASb4pgj2m9n2F/sE6mEbe1v6yGw=,tag:PqGiXdnP1AjjmLOVJk05Hg==,type:str]
    credentials.json: ENC[AES256_GCM,data:DcYOVszoIUcJiU+Pd4bYRM8d7Cmr6UExIb/40aEI/sRFAP8XAQHwR9xxHiJw41c8DvOlw0DryHclFmAT/ckehie1I9vbF9z+693ndKH3xsD7dSZyItKVUezuZlWUjn1O9nY3MFyr9lyAeJRGHPSviJlI92ZET0zatGdcTHamQy+kLEvvdn3zUDN6MxlgS9UurNzauegubct0hbApvyDv63oE9+rACYFF8rSvtuVq9g==,iv:IY5oCmdEPnvOBEQj/jM//MU7qpnwMMxIDIzEiUFl6ic=,tag:FA9PLAR2e8xiQ6eZE7lrfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcVlWOHBweTl1MDY2UFNT
            MEFqR0xIckRKMUo5aitXZXNzLy9YcFBVNm1NCmhYZkxUbmVhVitIaitYZE1RSm5Z
            djFGMXZ4NlVDd1liSTRHdERSSW9SZHcKLS0tIFV4SlJqM3RqUGxkdDZnVzBaSmgy
            NjJTclBlR1FjSk9OV3JaVVpuM2xVNFEKdFak7Y7FxEhxxKhKcincb+g+2OOr/VIX
            fVzpaq3lkHpLpjqlKPzNRUUxtGnLyz6qXiy5hU3o7pSwCLkgOILdTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T22:22:06Z"
    mac: ENC[AES256_GCM,data:7c9bTkkm8Bg6Q16M0snqXhR/AMInVGBFsHw12UAjjREg1GotSWen44HO59wyqrWgrelNwuDf+BEHPXWfU7WBTEiZDVdEH4TSVlfi/1iyrl0ItMBThseYj3U1h31Ze+e1V04OdQlK+EzoCEBaIrJZ6CijO6bv+fG6Li8eDSLS3V0=,iv:sAjoKMigr/a3riu1SaYiYxdKPGp8Bhgz3PVoRob1wb4=,tag:PR0IA+1rdtPz2eCR/n80wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
