apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:5yUcEMYRe80KvhwJGIfJROUa1sApzbtp54tNcvDZPYGcqnE5,iv:rP+jRnagG9HTSrAJIzuREcDxr8mlIk0dZJgjNiP77yc=,tag:1Aq238LITP7NaMPjDHltWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:PCuURQRJIKlmYGWSBuOtVcH9wi+4tG56fXGz8xJVCcfeDpI3Dmof1hYnICDWq0Es6kbk8f4K4ffNLdw6bXsjZjFtWmug5wXmc0L/0QZiZQSOzWQ1eeW+nY2r20jQoNlcUIW/Lb1IekUMsmPOuAOeL3F4I1MB6Uonk1pfj8iV/VnKrTT98oep2pa8FDvSBLSg20Ssn4s0fzQUJEvWF3cEzDeQvxCK1XaGPLj25H6c0A==,iv:tSNi/lzGbj/mJIRwJ3xfK0exRJAEYRPcijQpvmy/V9Q=,tag:sM0lTgPzayZui+aTQ2bKvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0d5eG9nMUhGVWZnYXUv
            b2EwMmZBeFNCNml5dFhyOCtNSUJSR0FPaUJFCmpuV082NEdBNnAzWFlqa0RJaXd0
            TnVFdzc4bHdFS1ZDUlNDNm5vSzZrRlUKLS0tIDg2Vzd3ZDJXZVc2dDIxRk56R2lP
            Wjgvc2VjSmpHY2UxZ28zVE00OVVkOE0KbsNnLn71620PyJbJk439XOJk0UK9w9hA
            zEyk2XLI8SUl/zqvypf2WrSfpxR6t9zifC/ruAM0TKHVM6UFwLAmPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T18:21:13Z"
    mac: ENC[AES256_GCM,data:wQMC4r8IDfpIXgTQ+gykU6iavP72wQ2mt6wsfe4Za+Ddf3vHim7fw/As50R9UjkNrwfkdEEwS6bTBanhD7QxRHfLS/YbuITZ4Dq/WbOi7Teb3olwxiEu7qdeeMlm3BePcCXxzyLVDbN/k8EOBCEqx3J7RX32N/U9ehcDI7wpKb8=,iv:7X8ytAKaBxjuRs3wfBTvlaj/LTcGQlFcWkwWVsTWnz4=,tag:ZOc3l5Nu564x2p2nNsaHbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
