apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:t03x8SLagorsL+N4whANi7c/kSwtxovPMvxMeZRG2pLw+LnR,iv:35/8c7JzVozxEhEpQtvN0dbyiw6hhhoPGFD0t+Mreoo=,tag:tipQ/UmtbprVnSftTDabOQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:pkKvY9Xcl4GY4k8IjRmF/+3PvStt/acMRflWlCGiojPLJOiSa/uyp4VAiuA7c92C9iiQSiDD5AlhD8EL0jSA+4Y9ZbirmRgIAuX436jmN/Bi0K6TcliBZaAs2cDOK+7o087IqstnM7ok9Dzk1hM5fF+OQpdw57NQ4Vm4TBI77gZA+AfRd/g4YCDOfkDI7fZcQazo47o4CvxgMGmwR0hQs991jSPi583LpCRh9l1uHQ==,iv:uJmACJi27xvlMgxZjQLyE9GzQuYMVMx6ZIT9npbjFs4=,tag:Zu6Nj82YQHCEBDwY6AzRZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZnlJeUgyWFFUNng5OXlD
            M1ovbDQ1Mi9McnlQTFJUbDBnVUtvbjIwb1NJCjhtcm91aC9BV1ZUN0ZtYmRhR3hK
            aEZ4RTAvaDJ6bVN2VXAxNm5aeTlrQ2cKLS0tICtpUTNFd29pYitDZXBNVmJjOXFi
            MXJZZDVSS0VqakVxWTRwdFg3OU52NXMKIste3+FgYMqUN9nsYiOu+oH05FP8bvCT
            NBW0+a0/JjRyRuYLS5Ye8f3LoKVUHWaFoYunw7Ax2Sn7fMPKDU7A4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T20:49:38Z"
    mac: ENC[AES256_GCM,data:Wv3bAhH3Co7YjB3ZPaykJBPvcejw0Oe75wQHju3uE+Cr8LA2HuXVJ2ZrWeiFmOmD3cLNV2TNwpkvmcXkHQd+r0QMewOs6TddcPBVjrmg0t2Z9dHh4EKKvL6JEGTyBXhhP0gmJkRL+25X6wFD8cPvFHZ99Da1xWXGd3hl/1PBqnk=,iv:L/UTzcAlOI0ne24D8qkoJZg0rCKMqvRrNdeQuixbcNo=,tag:lbjY6jf6B81pVcNA0uDuyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
