apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:puCG3v8aRgpqWg5yGl5am4WMK3iQ1fF3sDPTsiDGDxhhZHar,iv:BCCk2fXTRzsLK2SavajsV/6wCtzrUD4viFB2CqtywqY=,tag:a3FPVYuYxSO+VTPd5PgxLg==,type:str]
    credentials.json: ENC[AES256_GCM,data:/5v14PwnvyF3bHd7UGKsDJY/s+Y/RQsFrEGpxiGUldmRiH3mAlZBXDZjpMNt8uq4MHdNkQ3eWbkrxiYpl7maKJGi57MRgNZymo7HsO6r7AOXlfpZ8xbPLr77a9KTME4ahAmqumi6Y2VHNqYccezOWs5NiU3dr+Qw/djZeVKMcAUm5csZR9E8E8Bb1kCTeyBjttyTtRYC0JCVhSas2z1eMKTzS4vM3+7CImfjLq3KFg==,iv:M4qiZOief3hVv7XAnNg1CBzTWNjkCrkXHwJ9ps0b1Ms=,tag:e00mJMVDdlqQzFcHETsYIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVkc2NjEyTDQvMVN4b0ND
            ZzdyUEM1M0hIaDhONjMxNmFUV0hZMCs5bGxVCjVsd2pVNWhrb3VyQUFWTEU4NTZZ
            aTdKbVd6THVzdlVEaXhJNzZ6U1BuTDQKLS0tIENTZG5UUTV3ZDd0bjVXc1hkUWpl
            NVpaWUpkVTNuYlhURklLVUtiWlNzKzAK9vYziS2IWShNKw73JuSQevKUoIpWJlF5
            bPotQnmDygddzqZV79gTBxPvS+94R7fklEEpChtZugu4tAhJf7L8vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T17:56:22Z"
    mac: ENC[AES256_GCM,data:rd3rOZ7tAO6fl350v8CFWze+ogySYEZEFOT6w5hvhpid08mgGHPT8W+bqs8Omkvmjq1s8HRecHWXL5DSz76hJJftcgnOTkRe4bp0XxsvJb7IR88IC8HVsK2DmtR2YkZOlI6t6E+nHYcMuSGiWM4xuRehztevQzGXwBtYA2GplSI=,iv:u38hxYx8TXmtEQ6TLE1LSKx6ubr1eTaPSRQGgKxyPVg=,tag:OLa94KsPwfwb5X9UawUyLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
