apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Hy4skZ9Tr+DEPE552EMG7wEtDdvsOYDiH8BMWn2s8OFVD4hv,iv:0kOX5ei5nSefHX3yjlc4NKjUqooqUHBM2+7MZADcOiQ=,tag:qADQYsoRO1+0dbvoGZT3Xg==,type:str]
    credentials.json: ENC[AES256_GCM,data:eYwalviyBcSHe2/kSOReh+G0+YOPS1O5w0DPww+KTh6GLnSkjwsBXzxWTM07hqp/F8NtFGeNA4GZ3RXg0n2xUd6bzrx/CPV0iKI+hOfCy7bqApaPLN64yIwoIg/BkTwsrApIDow9gAcr+3R6k0CZwxbjku5qMzkmjV6BkVqdjFcs8x5A56S4DfKRF+ZaqjGw+7ZgqGyuGHqpbiIYDba6vzdUyuF0Jhnt0+fdUwTubw==,iv:0R2ognZiN8yEDStnxtkz7gUlyTT8juLwPc9aR5XsLWg=,tag:uf+mO7uJNiXjibNgsgczxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZEhNR1l3QVVKV3lIeENu
            d25aOHl6NlVGUUN4NW9kblJYdDF3S0xIRXlJCnoza1dCWXkzSENpQndyekNuRk5X
            R3lkK3c4bHZNMC96WUQyQTd6YmRCRE0KLS0tIFBtY091bVFOSUNDVThjUFpRYXcv
            YWdUNExUdnpKdk5nVzEwbkRVaFBZTk0Kpbg9OsWlYyQHsAs2vCu7+TnoGGyzLxtS
            OScZ19LS7vGg+MrRh+bstNaoBFuMGtbHDI3F6bQwwP9NtWgNtpxaFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T19:41:51Z"
    mac: ENC[AES256_GCM,data:b965FuHqxJ36D3bpbwGcwEPq+FTIfc14V0mRwjY69DF4w0xNSim5hUYi1J39VPAvQ8VtZkj3w8aa6RNvwEPYQcdm/1loAZH84JzQr0zr2vOcjyQdb2UTnma2uj5ntySyNCmTweKnCxj5nbNCfCf9zz33NgHI3q7uIiyDWjwqJnk=,iv:J456s73noY9ICtoTF0Wc5HRCLf6PPiNQTtHd7AgIlOA=,tag:0X8rFUsxG2uclUpH19uUdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
