---
kubernetes:
  children:
    controllers:
      hosts:
        "k8s-control-plane":
          ansible_user: "ubuntu"
          ansible_host: "172.16.30.20"
          ansible_ssh_private_key_file: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG00LrE9u/nPcBmidOdtsKrICWzjNJlMEfvMhinrJEvV"
    workers:
      hosts:
        "k8s-worker-1":
          ansible_user: "ubuntu"
          ansible_host: "172.16.30.21"
          ansible_ssh_private_key_file: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG00LrE9u/nPcBmidOdtsKrICWzjNJlMEfvMhinrJEvV"
        "k3s-worker-2":
          ansible_user: "ubuntu"
          ansible_host: "172.16.30.22"
          ansible_ssh_private_key_file: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG00LrE9u/nPcBmidOdtsKrICWzjNJlMEfvMhinrJEvV"
        "k3s-worker-3":
          ansible_user: "ubuntu"
          ansible_host: "172.16.30.23"
          ansible_ssh_private_key_file: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG00LrE9u/nPcBmidOdtsKrICWzjNJlMEfvMhinrJEvV"
