---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flamingo
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: argocd
  releaseName: flamingo
  chart:
    spec:
      chart: flamingo
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: flamingo
        namespace: flux-system
  values:
    global:
      image:
        repository: ghcr.io/flux-subsystem-argo/fsa/argocd
        tag: v2.10.5-fl.23-main-5958964b
