apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:8alRiKgLep0r9We5oiawg3ZkJkhRbS+NXrQTvQ5vVFtirUHJiqvNZQ==,iv:G3MzLHg6UKWt+ZoAPJUbdhrJn5THtqV1xiq2Q4VSou0=,tag:aDleYSgHeuusAAI6QTqxqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPci9vLy9IZW1lM3RKSlA4
            ek5QMDdVRDMzcjZ1Q09rRFhZTkFIUHBXUkNnCnV5VDdnRGZ5K3JWTEIwNTFNNkIy
            UVJkblZTRHBoU1ZWZjdlMWN2bnNnQzAKLS0tIDQ1bmRjOGpXdGJmUHkvSnlCSFds
            MmEyZW5nYWtTOU9XZlBnK1hsWjF4czQKXpO8j2ixsv4PWIRc74wKTQr6SnuUro0B
            AsZ7bbC8aT+EgoFbFk++LqoMkeiup/CoN/vmQ/OoF+oA3MNCi15mvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T20:49:38Z"
    mac: ENC[AES256_GCM,data:EAMBU+hZLmyZdVuaC3LL22cKyKlbVt7skEsEv8+124KdcPRf+XmNL14pQhmB6oSUcHuYT1TkY1qnE7+JbX4xTsmPRU5EF+r8qHxGkOhZfwPJ3cma74oECS4JiqjXJr2axUQwr5xKGZcBC01jCKgvwZYrRfCZ/MKor8iy8eM6Ap8=,iv:cYNO8AjoZliH23RVKtnNJSy4YcSPlmF5mx3+lxqHZRs=,tag:n4P6k7vJLNU25ypFSyDU1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
