apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Pz71ZXbPZRl6MRVsLrsvjPFiRv5ZjQoKHq9QNRC23ktkSf5hBbzaWQ==,iv:KEMXL6bNtE/JVUA+qgCAS4BSY3Vnw7AesY0L9uD11V8=,tag:lsJAwLAiou8gN1nCQAdviw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaEdlSmNsM2NkeHgxRlRq
            dFNydU50d2JTSlRLa3BZTVVwL2d3U09SdGhFCnlRQlJlMW5kdGVFNnVnaTZuNzhY
            TzFZTlUrZGU4azZ6WWNWTit4aFM4TTgKLS0tIGJjM1Q2WlNkMHF4NFRxc3hnTzF3
            dkE2RndWbGZPeXVCcXV1dWJWM3ByZkkKpLXf/k/8Eh0DTSjhKEgMvs5/egTwqd2a
            lNDmrLZ8nq+CFEhmxY51czf+L+uyEJSRMHHKezb26kDhNbplg0nCRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T19:28:59Z"
    mac: ENC[AES256_GCM,data:5DVct8acGyjvs/6t15UjVW7RSiUorUvf+bJQxdDoX0g5cG/btZ7vEfXM42ZJTYEQS+vGo+6Z2KF87mBM9PbGrvQKhFdkfSVdIB7d47voajx55NaUcUeAUTbdT+ndq1yHcIY2i9Rwd/pbiGDDlRCtZQFyF4oaNcslKq9soIG4d8Y=,iv:oDHrMHmCF12WIxI+uyYnZSKFjr+gTc/H0LO8Z2sPVPU=,tag:jIbmhoq7apomDfj5AQ7dmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
