apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:oSDp57smmOluJAy/7jlm5QoNRF1VKC1r2Zn5p1FCIee4brPmzJm6yQ==,iv:SlXEsyXMri2DSiG5d/JcHx1U/BCC0S28ybmAZD+XLGI=,tag:UYa+dOiOwJy0iO4LO7QYbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eWFNckRVNzE0T21mMEZo
            V0NFU1N2MVVPNEFnZDRINmpQaHZZUzFiNkQwCmprS0xjY09wTG5Va2kzTStKNkc5
            TUhheWRlYlVxZGtkMHBkc3gvMmlnTlEKLS0tIDJIdGF1dnF1dnIzR1NudnhWakpG
            K0p6aW1zemc5ZlJPOXMrL2VQbkIwSmcK3AmsAnosDmi1uxM+3/vzZy5seYNxaTxs
            fjgBezoPDw9OjGA/hfMn5TH1QNeG/IOxjxnMpgywXg/v8HamdWK1Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T17:56:22Z"
    mac: ENC[AES256_GCM,data:AoqDkZVwko01BdmTbYnmXnEnAl2qFuAQ9Sjx76Z/ZEtvVjcFSlgBNmBszarJRXGmzKayq159KPUA/1qVe3DYfdcEQuYOIfB76+Ps9u9nPcW9/GPkPGkquyO+vp7IpM1NVYybrF/JKS6w3zspPyOkxH+5jTZ1/Wy6X6yB1gjE6u4=,iv:6YCwRYimDnA/tgLLDZAvE7PqDg8qr7yvtbXyYGIs9Uk=,tag:NFiXY5zN3QtnaeJpHGe+KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
