apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:TGi0666biWF/wughC2OojHGmb3d/P20LDmZVDGRSF+MEOEW7X+AqxQ==,iv:O20nNQma13nbZ4f0jWWHG36Z/BPbFuT5OvCYI7kegDo=,tag:13xF8f7IohyIMAwuyB2S3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSelhTWmZEcVpyYlh4Tzk0
            YUNDZ2ZMNnBMTnp5V0hKU2JZNlhMdHZNWEdjCmFuVlJvQlBBMVh2VHNVSTJCZmlC
            Z0w3NlBpQXFlVlpIQ3hQT2xFd0hjdTQKLS0tIFlyOTFCeFBVYVZmVGlheTA1Q2E4
            TzRGanh4OVR6VlBLWFdqOXRPTnl1TUUKggr4f7C+srU5sIaXixl5uTOZ3iYtUFL6
            GxNC1hj02pSUkWTs9Z2epBh4AZ7EVgxI41BPV+k29e6L8g01Eag0aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T22:22:06Z"
    mac: ENC[AES256_GCM,data:MdCZFXyfBUojrMbHKpsLhlhRgGY4c10C7KFeKIdxVx5YnzCk7Y+kpfP7wqTcjbKiblkDz9zG/S9/gGiuX/Z32Y85Y8ZOn3a8MISS2T/E4uCfMfuFnBOUvKwxwzkPNCoerdqBDTvQUbLLldjoZCJAOIptj0y1P2IzpU7fm2T+qu4=,iv:8zXr0egMuyl3sD4fIfh+T5rKhUyfnd3Vllu8EjHJGCQ=,tag:h2c+mVBLKkT0GsEgyEG25g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
