apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:AYPAWIOY2vQGE17b5HQRDVG6OIlMN7LK4OxTBA4KJvMPQAQZoV3c2Q1+XVE+ritMYmTtNNaIYPqZIKfatmrDGPHDcA6pw0ju/um0ROdNFjYb0CDC4w2Xl1Gnly0taQ==,iv:F8Ap8EHqJBliuD4Y8Oa3uBHBcfIOGPfMekIQp3gwEf8=,tag:qWLCmu9pFi9u0IbR31J9GA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:tZKiYhHpKPG1DxSK,iv:38KAm74wHoJMlYcZeL+pQgA8jsGtgpdBoi1u31rAyzg=,tag:speVAy6oE7xora+sHzS9dQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fkMOGzR+ADCukYCWldI9UlD/mEU=,iv:0YzQ0u01ECjqAfwFK+AUjjf155srMt1D6i7pAeMiHOQ=,tag:KBYl0wDUSnLx+gbJbLZtDg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GDnjWjXIAoWLOidWwcCtnRFtVlyrPS7zgyw5uMuh+AXyVjAQ,iv:NfDl+TCUn+Vmv8V1MxF+ryop0SU68ma113Zl2jrf18w=,tag:K09z8VoJpnkJF3wW5uaDzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMjQ4dGNEcUR1QjZ5akZl
            QXlwQUxtOTBEMm5VTEVWR1BxUnpPbXJDclFZCkhMUXdRVWsxS1NCaW9zUngxNUl4
            TkdlNk5DWGhGeTNlc0dyZmVqWlhQaTAKLS0tIHNRU0MrdS9YSG5PYWxhSFRzeXB5
            YnBreUxlVGRwMGJGbFoxSVVuMzZIbmsKHZJQ0+k3h05HHPeWR7lCpyonOuO91jWh
            N/WblFOJhl7suXygoUqBCBJg4s8OCjbM8nXZZNnjOT3V6tSdMRZy/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T18:21:13Z"
    mac: ENC[AES256_GCM,data:QIbt4S2NtkjaizU1E5lJtM2sIuGT0H492npFXctWkpKLZnWhVTRQNPBkH7GqY9p4Osy0jPyx3rEjatIK4AisA0JhJs5ezVxTnia+PhdewfAcg/BXo7osX+n9wVMMs+Zj7tqwG3sAagzyl+NbY9so170tJn9SN0ImeLfM87eDQv4=,iv:vJUxtU4J+fxtYM6Zjm7qMlY0LcOBshtH+NLtzzCQc/M=,tag:3r0IsGtJyZd+3F6E68377A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
