apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:pitL25rWr9sQUAKT+WiyoFVV+cViaEhhpJZ5mtNapzH4KU4mPrceD8NKhMPK3PjAVIQsvtI+58AX7dRWhC+XjzXsJAJ3yzowcmDUKr9Jmgkx79AT32/M+hUfbv7+0w==,iv:xWBIPcwtAGajKKDius9iMrxAOjTY65AwQDxG4ws9N78=,tag:ns+/ik0Km+dwGC2aM9VwwA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:xEiSdYdajxdVhGYC,iv:0Yf/crPKSAGc0GPJexmXpESOdOliYZ42JA2ZLihAsdI=,tag:2BqvdcLKg0o4UnI2kyyH4Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:aTJBihDfUYcx2Qy+7es+HHzhZYc=,iv:+AE6aUxNSSdc6/UY/m3LEeVm+nLzfz55pyTRvkRXvqk=,tag:sd9bw9Xovkulx4KaLYhkZw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gL/qxMXyAfJYU3kyy1wqtbfTc7UY1kWn1OPb24J4kGsaMShU,iv:WL8B9K6P9zzjxEg8JpiUKs99Z3/cV2M/+pP3Cj2B86g=,tag:plNHh9dbr6BEkLzDpqZ8jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZ3ZtQXlGNVhod1Jic0tj
            RHUrekN1S0s4bWVxeTJCLzc1RG4wTnR3N2pJCmZyWWc0MXB1dFdxeXptc0VXakZp
            YmdHNUk1T1lvSVBzcHZVaVo2ZFkvcncKLS0tIDVCeE85aG9jdTM1bjlvMmExZUY5
            QnFsbkw2aFR0YysydkhzM0docDlvVDQKN292I11ruVA78Y3qRsWSukgCIPO24GNa
            s8ZYNni/+lm1w1zc1ccDHLinByRKqIpkDNwOcGZkVFKXyNg5wk/ZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T20:49:38Z"
    mac: ENC[AES256_GCM,data:BgSxW9LAc9YCnGROuHb5PmhHIjYEW35/zQcbaMz2nJQD0jlyoG8bwJQTrOZX2IDPs4yyRReJbrr5QDagzaSA7nG1AjeWMPhA8NmyrGdph9plzewrT1P4wXdc2d3yWk4q/WMUH/BD9KKCijFPFj7QyhMDKORwpXieUJ5tXafXwy4=,iv:HtsZ4sQWSWxgZaQxQWD+JpZWpqj914KHN8Ux2ZA9tG8=,tag:FEdXi/yS8ZIgIBdlijJ1XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
