apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:I+rRlsnchoT7QN6FXCkHH+YKpk+YOzzMiJ1znRbiT3L2MfFBizsScfEhL7aMUGKgMEmk9Y5AkJKLueSx6ijsqnumjEb7gsuIgzOkyytudwvxRgQcXkuEjzAMG4rgAA==,iv:6hRyDfl+ZFDykYbKFflPNjJ+3MM3crFDVhnpPhtSQbg=,tag:fNhLG+kwQZdMyxmQmmAs8Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:RKnO2TZFbRD+aCGU,iv:eTK9E19ZKbbia/jBlHBbP1FKWaHqs0U2f4zpdwjmU+0=,tag:RWQ64OieS1lnmKWiyCelGQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WDxHlt+AGHLnfe8U04LmEO0T46g=,iv:Qy3cJPaZ9MGZPSNKQMbKIOcWiis3L6jE7mhST2F0nMA=,tag:PdQLmgrelEhjE4KyBzt3vA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Scpvl+2ArUDTIqDhX9/kNawZWGrHmgZ1d8C9qzcH6HIenL8D,iv:3KcC8eD6RMjEYIKijWXi/hpsRVx4tulQ1kCaYlpUHPY=,tag:FkczyoyTyBV3SsZOkxAWMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNHNxUnQwcVNjbDl2eS9C
            TU5DcDZOUFVqdjdpYXc2QnpGL3NjTzczdEFVCkkrdHloUjRjbWlJbEphblExeEMy
            bkZSNGxMNk9BYTIrcDVCOUZIaUZFMTgKLS0tIDNOd3I5bUdGdW5OdkpLVWd2cTBC
            Ujh0UUl6UHZJL1EyWEcrZVJkZDRhZ00K+qbiDfKHUevZN8m7ntCOTA3zHhDb/Qbg
            uHIr4NNIFfDIjFp79odRzACsSMlxoFX6bhuKn8Dvmd3eaI+duu1Rdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T17:56:22Z"
    mac: ENC[AES256_GCM,data:FPbX15sBmUjNdzy9cGWPJAAm/Rq05uFkFK9EsR8l7b4AsD67My9Oo/0y0mh2CEJWefCaHBx50JuHsUgOEpsC0iRb2p35X2AjkWxzGezCilJbHL+QKEJziS9JekOusql75n6gOSn5CUTmx+rD7ZDOfiNrJonALwmYz7F53pdtEUk=,iv:J6bFzUdT/abwrmqta6QGlgJlZOhDMQYv09gS3whlKEI=,tag:BQaezZp+tqyev6GK8Z/tcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
