apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:92LwdSQ2oEj9ZWxToqnHVZnQ41b/IBSbDaieFSRe31UthTX4NKMyC6ZNBIRIFe0+U4tOEElBJqqFa/oVxAULp0Hp6jiPTWM/7uFaXKIB6UsOcPPcK76K5ccReAzIug==,iv:x4pxycgemb4jwbroSu4BR/l31/T9NXFoQq8Yc74HL3E=,tag:OaAUdQjq+c6M8ah8nSehRw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:DeQnEswzLS+eO+P7,iv:kgmBxFIPVDfeykY3KihRnmW7uMC0rurseoL3rTWVyxg=,tag:bdqzpOt20RQS3YyfPunyUA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OzwVh8CeXx52DBVJUg3EEB6cb0s=,iv:bWPrlphIMYaFNozpSfXMtNgUg45nCQlgaUia6ckh3g8=,tag:wSW481CKy7KkOw8D57IuYg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TDtqPgIygZL4PLd+L3vEieaW3rVIOqPQrB2oMCkYjBjLNmz8,iv:mrrheMFvCtPJoFW9baZT7LvEIcDk24faEvldn5CtUeY=,tag:SJAusLylwClRAjC94St/+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb0FYWHBGTm1naVlKYkt5
            dHhwNnlkTkViVkZUY1U5eC9oUmNhSStqdFdrCkloK2hVYk8zTDJEeVVaSy9sb21n
            d1pCejhHNUlCRk9ua2lvZTNYR1lUdzAKLS0tIE41S0J1SzIySVpjUWZ2UzV4VGxB
            OUF6U29vSGU5dmYvai91c3drTkxMV1kKpY/970u9QkECG7KJNrCRrjdhvaWLSkXy
            hXIEd/UP6I8qZmRL4YFLmi6vOQnUZ3xgtKmMx5aMoMBrP1fgR5+Ulw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T19:28:59Z"
    mac: ENC[AES256_GCM,data:IPWVsq2CGciJ3UwmGj88JWerExFur2qxyPPkCUBx6TtbKaWLBUvNuPdzP/H77iGdaPfljwWqfieNQ4Otd5EyNDD1qOuuW+GIrzMHmsE8AIaLx+HDqxUJWYPWbnTKajbzuHwTKxoHwrAWKRBFEjHlTNaI6DQYbRfvYbm/TVSqfJQ=,iv:S6Bn8DGRQvJc9zxW1TAKOss/zTdB9G4rN5v0TDSTNJo=,tag:Rru1GCAmAZfDGoKc6W2KYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
