apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:kXN4dZUJ1LN56pU1T34hrnnHWHtK7HpoOPpejuHzHXM8rjmvrX11uUGROLjQHIGvKLTVoGqdoJzT4pUc1zPFAG7I8afhVz3+PaTZKeJYXf4+O+IrMe3GxKAm1/SCWA==,iv:7u5jzNUTpIazIvC47Szh7kHy7gHVt1S3bHkPi17fdCE=,tag:WHV98w3Aeu2djlHQitw0sg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:IU4pcM4kSTubAD53,iv:1CVDP9yEYibfV+p+AX3E/QihJ9VD8uBlyPfI8zUzzbQ=,tag:M2iDjfJtOOx/pKL2q2g31g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DjUhto0mZc8xH9J6wZ1Kt8pFBDU=,iv:+4okau0UAiy6ptiiN+y7y0OgB/74rSgKDNwwaLoWFZM=,tag:KUa6j5fC8hJLcZh4xvc9mg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3lAC5vKuTwmNvYVnHo4MGPA6lkUV1NjFXpOx0T0YODdhkwoe,iv:eb2nOrjn7pjeIlNjqf6aeakvWkfZQxKfqIG8uzXHsK4=,tag:MCik/OcQM0j43eQ9EXG26g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2t1ZndXZlQyakt1RkY0
            MjZHb0dnR2g4UTd5Y2RVemlYRXdvUm1Gc1M0ClRPRGtrK3NydHN6dHJ5QzFvMVRH
            WmpwM3lHQmVmK05ieTY0eTVPRVF0YUEKLS0tIGF0Z2VCTmJrUDA1anhvUFduY2N0
            VzFwN1VneVA4MlNJZ0NnK1I1aTl1T28KUTuJ7Ud892OvcPpqypbA3a3GaHr1k04w
            5OETFaQ8dgZmvPf3ptx4LPn7KYbTptZLB35Sf04Yzuova7zZGj+Bgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T22:22:06Z"
    mac: ENC[AES256_GCM,data:VL/IbDISwUT3BqCQsSvRy+6Aa+2TtVhgtrjTFsem6Vm3CtzjK1G5y7pPon/JBYoh9raMN9Jjj9c78I1p/6sw83EnVCsXYW08m2Mt0Rr29pS94uolbK47pMXtrZxh72vgLuUJSYdjtSpE8fx4ve5eP4AZ1XCYKluAfI70n2hWNF4=,iv:Hnv78WtQe1tnSEyd3U7HU9W5ayglHHXBsefUoEl747E=,tag:jVrmkZ3EdQMrweKBLWE6Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
