apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WUtxTTNta2NtSXNndS8r
            aWZSTjUwa3dhZkx3akZnNFVDUXZzSGRnSmtVCi9YZ1pnSjQvTHYxcW1va2F6UXhi
            dkxnc0pVbjU3aFA0K1JNYXVTN2p4Q2sKLS0tIEdhci9hYjQzR0g1d0pKRVJQOU1j
            L0oyOFJNbEllWm5qcGhIL1ptVU0vT1kKTLu8X28wP2jw5JDoZkbpW+05hOGZ2xfK
            BDrgMz7uIf6PaQGQ+XKVd7vCJKbA+AFvFAjKjaxq6eb9cUVTv5vKjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T22:22:06Z"
    mac: ENC[AES256_GCM,data:yVjCdtc/388ceDNORCdW+3ZrrCc+RC7ku7uJ2OHVF/egi4EDs0Vo3BUT5YPBXLUmJZkLxlAG87xBlqFkD92r8lW56itur6/3PZcUPdz2UdOf/+EiNQA86s7gUsPzxn3Z000Yt89spKZ2kh+fpgivPyJwyktWlDJj7VZ2Nuz0vUE=,iv:S2JfE20olDw+MbrAC7fJjlh6mrVlIs+lyR3hkt6LnXI=,tag:7jNRrQBkHaLDKt81yZ8LHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
