apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVWNGSnRkb1lrTENnbGZ4
            UG95REI2aXNIY1pndnhtc2c2SDRRWjNqYXdnCit3OXNPa3lVT3FaSzlRanUxZzdV
            YnEvL0s1alZhWU13OGl6V3N1NzRkYTAKLS0tIGZDNmxRMFMydXhEY2kzd1NkejI4
            WUE3QnFGb3l5SzVabDhzbWdZRDRnbm8Kk77zVyvOBDcKHRBvPFwMaSx0Bfdnc551
            oIulzxK928WkkXeJNHIVgs/B1Wwq7ezfOPvxlyW+O4JwjpCpIhRuVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T20:49:38Z"
    mac: ENC[AES256_GCM,data:Xo/GREEVnwGBsphwtoKSQ42JkFm9XkbYhSUeijD8FYSaRvQpk/YDJSbgC8vtHO1q6uLiTV1oewLSA7x/kSDa/IWW7bTGlyspeToc/qMHK7el9LJLDNrciNwYdUrB3OthH1hPGOUUwYgbnT6h66KF4Yuxl62jgK3VtLQFtyef4uM=,iv:ZZvezNDhOEf0ZDRzfv5KmtFmTYjZyFz8iIVDte553cE=,tag:V55xff2kVOTYUt0QtkrZmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
