apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:L7BcB5tfHTAj+lfjIhcah2z01lgP4K/36nndCgJX8aA=,iv:XkMaeOCHOOnzm5l0CtCUa8MPo4uitZjwpkac/NtG0y4=,tag:Od5JmP+/+0+qaC1EzNfUoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdzMwbGFuWXhiYkpDLzZw
            ZHdkdVgyQ1BWSVU4RmppRmxrNVJscll0SkUwCkhsUzUvdVZWMUNDVlNDMlJxVGtP
            b245K0tiOC9HRXlMYUdlNm9YOHlWeTgKLS0tIERocGNMVmlzSjhEbmxzc1Z2OFN0
            bEFqOThCR0QvN1hXeFdpSGJjM1BqeVUK3LRN8UmiwYG1f0lJ2KY2dOiNTm8bIvX+
            Qz/N2emHlcSLN+uuHRfAAvbrCM0M820C3DTSsrFRpBp8m69i8btwWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T19:41:51Z"
    mac: ENC[AES256_GCM,data:N1Z+a7ihE05PyEN/JB+VTczPZAi65eMRqRw2b5mNnC0esEm/C+9vi+HkNrfWkU/pe7ZkggLb4VDRMu7eAEUFpFkAK17SZy+0LXMX0XHn9P6M6i1e4r0yxfBN7H2JkiPYtaERBHRjaeVlNQfTs20lWX9w1CxdIdrjRTPmH9+257I=,iv:qqZJxHwUAbkJk68tdXkfVv2laU8IBh2n4fw/Fw35X5M=,tag:OBSEMhL8atFvBZb3Qa3jpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
