apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9ZbgUou+jeeNzz4ZIADLWEx+qNPMaSN/m6IF24daR9tlz3JN7KrKFA==,iv:SdCkaZE7E2/NASB+pJea0eBS7yXPkKIEr8wM9pnSLjg=,tag:aOIpfXgC+6eXF7fCuIWXsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14huhffyz7qwdglcu25qm2wyrjs070gr2g0m99yd0amkkpkp7ac9q7c5tc4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZTNGZ3AvbVdiTFcrSi8y
            bVlmeDhJdHRMRjJFUHZvT3VYekp1MWxpdWhjCjFwY0JCOG5hczRHNnI3T3lhNm9F
            NS9jYVRMeWpZMTVDZ254UG8yOTJ3NVUKLS0tIElsM3p5WlZqdCsrUVZiaXVMcWgw
            V2paU2s3RWV2NU1mc09kWnRhQ0NEZm8Kj/ClwY2EU5sD3Ql6oYoviIqIQNKKcyLF
            jyfWNnUSvekymD4LvUoF3DoS2yAo0BN/SkJoorBdg1g6f4g7KUn5Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T22:22:06Z"
    mac: ENC[AES256_GCM,data:Z23iqBjDLZ27B4MNNZIge8ODnDdAiUqG4DS1lMb36Qag97WBGDol2blgV56yZxBQHdRU5zhPx2ua2spHZivVXOTz6B4F+3JLdNNhy2cgVJrzqd5yl43h9PtmqMXY5Yw399ZKe5GM8rLfB38GAJgJbyL+y7CN/2WfHpAvPq2Je1U=,iv:2y25+g+dp3sEpU0PPgGnkpcKorB2Smbe8zWcXWZN4/c=,tag:7aMopfYHfWszpeijM1Iz1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
