apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:jh802YuOhPh3l4GQ4BviFOJZ9DZwJ29ennoS8FoOhcfMBiGHhrWN0w==,iv:qQKLBCsHCjzb/Yk4qYYgF8k3uywwipzkAeKkNL8X4Rw=,tag:w4pL6Zd5wPS8+iSOUMKNqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz4wph3m4n8vu6ay8wj0pjsfkcjrxu89ja9htmw5s3ftvljruauqkpt8e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcFZnRDBBTURsZFYvRDFD
            Y2d0eWJ1WGxoT0Rsc0I4N2tVK0hqN1RURURrCk5KSTBRZ2NxYlY1cUQvK0xDQnJG
            UHZSc2xhTUIzYisrb2Nybjd1MHRmU0EKLS0tIHBnNzFCL0p4cmFpRzNoUTZ2a0No
            aEdiOE5XOWV3SHZucGhMdTQxVkZlelUK2cVQknnkud9R2Us2ClLrb0FSaP0egTeh
            uK0pbSRSTLkf7ZPPzCIbRuqA4egs4VO3dsInfmLr+UOHjw+Slpb8SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T19:41:51Z"
    mac: ENC[AES256_GCM,data:idZHrmDZGB5Aoc4RdNGpZgL5Yz+To/vfL5AndLYHoSuQGkyzmuoxA/ax/q0LB6/rQtqdkrh6AYIcwOt4qdEVHlFCxHhAZ8ALYnLy8odujhdoB6J+pTOTq7ealzNrGmZwQzAr+XMZ9L+27vsRJS00MFxKij3bA/D4lOIfKNGnzXU=,iv:FlZCcFep82T9YaakKov42L57BmLCgAVPkqQnnTmFbUs=,tag:QmQn6A8bG1Bf/Rlh2Hek6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
