---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
      version: "6.10.0"
  interval: 1m
  values:
    global:
      image:
        tag: ""
      installCRDs: true
    controller:
      metrics:
        enabled: true
      resources: {}
    repoServer:
      metrics:
        enabled: true
      resources: {}
    server:
      service:
        type: NodePort
      extraArgs: []
      logLevel: info
      replicas: 1
      metrics:
        enabled: true
      ingress:
        enabled: false
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        paths:
          - /
        hosts:
          - argocd.lunarops.net
        tls:
          - secretName: argocd-tls
            hosts:
              - argocd.lunarops.net
      resources: {}
    applicationSet:
      enabled: true
      resources: {}
    dex:
      enabled: false
      service:
        type: ClusterIP
      resources: {}
